spring.application.name=agent
#
#spring.datasource.url=jdbc:postgresql://localhost:5432/mydatabase
#spring.datasource.username=myuser
#spring.datasource.password=secret
#
spring.ai.chat.memory.repository.jdbc.initialize-schema=always
spring.ai.ollama.chat.model=gemma4:26b
#spring.ai.ollama.embedding.model=embeddinggemma:latest
#
#spring.ai.vectorstore.pgvector.dimensions=768
#spring.ai.vectorstore.pgvector.initialize-schema=true