spring.application.name=agent
#
#spring.datasource.url=jdbc:postgresql://localhost:5432/mydatabase
#spring.datasource.username=myuser
#spring.datasource.password=secret
#
spring.ai.chat.memory.repository.jdbc.initialize-schema=always
# If you replace this with ministral-3:8b or granite4.1:3b, the tool calling works correctly
spring.ai.ollama.chat.model=gemma4:26b

spring.ai.ollama.init.pull-model-strategy=when_missing
spring.ai.ollama.init.embedding.include=false
#spring.ai.ollama.embedding.model=embeddinggemma:latest
#
#spring.ai.vectorstore.pgvector.dimensions=768
#spring.ai.vectorstore.pgvector.initialize-schema=true
arconia.observations.conventions.opentelemetry.ai.flavor=openlit